# Generated by Django 2.0.9 on 2018-11-06 14:50

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='45.256, -71.92', max_length=100),
            preserve_default=False,
        ),
    ]
