# Generated by Django 2.0.9 on 2018-11-14 11:40

from django.db import migrations, models
import django_google_maps.fields
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='straight_to_site',
            field=models.BooleanField(default=False, verbose_name='Перенаправлять сразу на сайт конференции'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text='Ширина 1110px', upload_to=events.models.image_name),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='345x280', upload_to=events.models.image_name),
        ),
        migrations.AlterField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(help_text='XX.XXX ,YY.YYYY', max_length=100),
        ),
    ]
